POST http://localhost:3001/api/patients/
Content-Type: application/json

{
    "name" : "nimi",
    "dateOfBirth": "syntyma-aika",
    "gender": "female",
    "occupation": "ammatti",
    "ssn": "1",
    "entries": []
}